spring.application.name=gamestore

spring.datasource.url=jdbc:postgresql://dpg-d6tvghqa214c73cr3n00-a.oregon-postgres.render.com/db_deploy_gs_hope0013
spring.datasource.password=vg4ZIYBReZfFx9nAoTxpPj0Cvo4Q4joC

## Configurações do JPA - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

